# Generated by Django 2.2.5 on 2019-09-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolyo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolyoicerik',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='portfolyoicerik',
            old_name='title',
            new_name='islem',
        ),
        migrations.AddField(
            model_name='portfolyoicerik',
            name='isim',
            field=models.TextField(default='İsim', max_length=60),
        ),
    ]
