# Generated by Django 2.2.5 on 2019-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TakimIcerik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog İçerik', max_length=100)),
                ('description', models.CharField(default='Description', max_length=100)),
                ('keywords', models.CharField(default='Keywords', max_length=100)),
                ('author', models.CharField(default='Author', max_length=100)),
                ('isim', models.CharField(max_length=100)),
                ('pozisyon', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('pinterest', models.CharField(max_length=100)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
